nameOverride: ""
fullnameOverride: ""

image:
  container: chefbook-backend-tag-service
  registry: ""
  pullPolicy: IfNotPresent
  tag: ""
imagePullSecrets: [ ]

config:
  develop: false
  # Leave empty for stdout only
  logsPath: ""

  postgres:
    host: ""
    port: 5432
    dbName: chefbook-tags

secrets:
  postgres:
    name: postgres-secrets
    userRef: user
    passwordRef: password

service:
  type: ClusterIP
  port: 8080

replicaCount: 2

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  # targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

podAnnotations: { }

podSecurityContext: { }
# fsGroup: 2000

securityContext: { }
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
# runAsUser: 1000

resources: { }

nodeSelector: { }

tolerations: [ ]

affinity: { }
